### PR TITLE
Add a loop unrolling optimization

### PR DESCRIPTION
**Pull request by apaszke**
We like to write n-ary helpers such as `split_key`, but they often end
up being used with very little arities (especially binary). In those
simple cases, we end up introducing unnecessary intermediate arrays,
index casts, and array indexing operations, that could have been
simplified to a direct evaluation of the body.

This pass adds a simple form of loop unrolling that tries to counter
those issues, under a potential limited code blowup.

### CODE REVIEW

**Comment by apaszke** [comment]
A good way to visualize the difference is to consider the program
```
:p
  [k1, k2] = split_key k
  (k1, k2)
```
which has the following simplified form:
```
v#0:((Fin 2) => Word64) =
  for i:(Fin 2).
    v#0:Nat = %cast Nat i
    v#1:Word64 = %cast Word64 v#0
    v#2:Word64 = threefr.1 0x375f238fcddb151d v#1
    v#2
v#1:Word64 = v#0.(0@Fin 2)
v#2:Word64 = v#0.(1@Fin 2)
(v#1, v#2)
```
that turns into just that after optimizations:
```
v#0:Word64 = threefr.1 0x375f238fcddb151d 0x0
v#1:Word64 = threefr.1 0x375f238fcddb151d 0x1
(v#0, v#1)
```

**Comment by apaszke** [comment]
And of course, the optimized form exposes a nice opportunity for constant folding threefry completely, but that's for later (+ we might want to only do this if we consider the body of threefry "cheap enough").

**Review by axch — APPROVED** [review]
I assume this still leaves room for later inlining loops that are only used once, etc; but it seems reasonable to merge now without that.

**Comment by apaszke** [comment]
Right. I think that inlining will have to run before this pass (I don't think we ever want to roll things back into loops). But small loops that haven't been fused with anything (like the ones generated by `split_key`) are still worth unrolling.

**Pull request merged**
