### PR TITLE
Portable syntax highlighting

### LINKED ISSUE #176: Portable regex-based syntax highlighting
A bit of syntax highlighting goes a long way towards making things more readable. Right now we have a [little emacs mode](https://github.com/google-research/dex-lang/blob/main/misc/dex.el) and an independent [syntax highlighter for the HTML renderings](https://github.com/google-research/dex-lang/blob/main/src/lib/RenderHtml.hs#L67-L105) using parser combinators. Does anyone know of a portable solution that lets us define a bunch of regexes and generate modes for vim, emacs, sublime etc?

### PR DESCRIPTION
**Pull request by sureyeaah**
Created portable syntax highlighting using Iro along with a vscode plugin.

Fixes #176

### CODE REVIEW

**Comment by oxinabox** [comment]
Apparently the textmate format used here for VS-code is used in a bunch of other editors too.
(TextMate being the most obvious, but also SublimeText and [Atom](https://flight-manual.atom.io/hacking-atom/sections/creating-a-legacy-textmate-grammar/))

**Review by apaszke — COMMENTED** [review]
LGTM, but please let's avoid checking in generated files to main (especially ones with some default content we don't need like the README, CHANGELOG, etc.)

**Comment by sureyeaah** [comment]
Alright, I'll move those to a different branch.

**Comment by axch** [comment]
Is there any interest in reviving / completing this contribution?  If this PR has been abandoned, I will close it.

**Pull request closed without merging**
