### PR TITLE
Add missing ProjRef case to linearizeOp

### PR DESCRIPTION
**Pull request by tscholak**
title says it all. partial solution to #713

### CODE REVIEW

**Comment by dougalm** [comment]
Thanks @tscholak, this looks great to me!

Since it's your first PR to dex, I think there's some licensing bureaucracy you need to go through. Usually there's a bot that prompts for it (@googlebot are you there?) but maybe it missed this because we're not proposing merging into main. Here's an example PR where the bot was successfully summoned: https://github.com/google-research/dex-lang/pull/387.

I think you just need to go to https://cla.developers.google.com/  and sign the CLA, assuming you haven't already done it for a different google project.

**Comment by tscholak** [comment]
Hi @dougalm, I'm glad you approve of my quick follow-the-types hack. I saw the response of the Google bot and signed the thing as an individual contributor. I'm not sure how to rerun the check. Can you do it on your end?

**Comment by dougalm** [comment]
Awesome, thank you. Maybe we just have mention it by name? @googlebot are you there?

**Comment by dougalm** [comment]
Mentioning it didn't seem to work, but I was able to force a rescan by following the links. Seems good now.

**Pull request merged**
