### PR TITLE
Added a Storable instance for Float32

### PR DESCRIPTION
**Pull request by cyntsh**
For example, this allows the casting from Word8 instances to Float32 when reading floats from file.

Co-authored-by: Zoe Chen <zoe.chenzizhao@gmail.com>
Co-authored-by: Adam Paszke <apaszke@google.com>
Co-authored-by: David Duvenaud <duvenaud@gmail.com>

### CODE REVIEW

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
Looks great, thank you! It seems like you have a few comments with different values in the "author" field which confuses the CLA bot. Could you please try squashing them and making sure that the author field is correct?

You could also try adding Zoe as a coauthor by adding this at the bottom of your commit message:
```
Co-authored-by: Zoe Chen <zoe.chenzizhao@gmail.com>
```

**Comment by cyntsh** [comment]
@googlebot I fixed it.

**Comment by cyntsh** [comment]
Alright, I've rebased all the commits, thanks for the pointer! 
(@chenzizhao @apaszke @duvenaud googlebot just needs your consent)

**Comment by chenzizhao** [comment]
@googlebot I consent.

**Comment by apaszke** [comment]
@chenzizhao have you signed the CLA? It looks like we need constant from @duvenaud, but I can see a "missing CLA" error next to you @chenzizhao

**Comment by chenzizhao** [comment]
Sorry, I just signed CLA -- has the status changed on your end?

**Comment by duvenaud** [comment]
@googlebot I consent.

**Comment by apaszke** [comment]
Thanks everyone! Hopefully the CLA bot will not be quite as annoying in the future.

**Pull request merged**
