### PR TITLE
add ixkey2 to make generating random matrixs easier

### PR DESCRIPTION
**Pull request by oxinabox**
Used in #33 #47 #50

### CODE REVIEW

**Comment by oxinabox** [comment]
bump

**Comment by oxinabox** [comment]
bump

**Comment by oxinabox** [comment]
bump

**Comment by dougalm** [comment]
Thanks for the bumps and sorry about the delay. I'm working on a significant rewrite ([this branch](https://github.com/google-research/dex-lang/tree/nexpr-rewrite)). I'm going to hold off on merging these PRs until that's done.

**Pull request merged**
