### PR TITLE
[NFC] Rename "Embed" to "Builder".

### PR DESCRIPTION
**Pull request by dan-zheng**
`EmbedT` is really an IR builder type.
"Builder" is standard terminology and easier to understand.

There exist both user-facing ADT builders and Imp builders.

---

To be rebased after in-flight PRs are merged to fix merge conflicts.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@apaszke and I decided to remove the `gardening` label (cleanups and NFC) in favor of the existing `maintenance`, which covers both CI & build fixes as well as software maintenance (code cleanups and NFC).

**Review by apaszke — CHANGES_REQUESTED** [review]
Let's wait until #457 lands

**Comment by dan-zheng** [comment]
Yep yep

**Comment by dan-zheng** [comment]
Ready for re-review now that #457 has landed.

**Pull request merged**
